language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '16'

notifications:
  slack: pruebaisespacio:lexNQuBGm3hQo05XGMDARagV

deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: 8f757e44-1d6d-45e9-a2bd-be6cde8f9c27
  app: integracionis
  on:
    repo: EmmaMolina19/CI
