language: node_js

addons:
  sonarcloud:
    organization: "emmamolina19"
    token:
      secure: "22b0e7be183ddc5ad6f13ef329e150a25a58e149"

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '16'

script:
  - npm run test
  - sonar-scanner

notifications:
  slack: pruebaisespacio:lexNQuBGm3hQo05XGMDARagV

deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: 8f757e44-1d6d-45e9-a2bd-be6cde8f9c27
  app: integracionis
  on:
    repo: EmmaMolina19/CI
